name: continuous integration
on:
  - push
  - pull_request

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: |
          python -m pip install -U pip
          pip install tox tox-gh-actions
      - name: run tests
        run: |
          mkdir -p ~/.kube
          cp .ci/kubeconfig.yaml ~/.kube/config
          tox
  e2e_tests:
    name: end to end tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes_version: ['1.15.7', '1.16.15', '1.17.12', '1.18.9']
    steps:
      - uses: actions/checkout@v2
      - name: setup py37
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: install deps
        run: |
          python -m pip install -U pip
          pip install tox
      - name: setup minikube
        id: minikube
        uses: manusa/actions-setup-minikube@v2.0.1
        with:
          minikube version: v1.15.1
          kubernetes version: v${{ matrix.kubernetes_version }}
      - name: run tests
        run: |
          tox -e e2e
